<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USER-20150602CO" name="api.test.demo.Bindcard" tests="1" failures="0" timestamp="15 Jul 2016 03:05:37 GMT" time="2.648" errors="1">
  <testcase name="bindcard" time="2.648" classname="api.test.demo.Bindcard">
    <error type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : expected [1] but found [0] in method : .bindcard(Bindcard:38)
	at api.test.demo.Bindcard.bindcard(Bindcard.java:38)
]]>
    </error>
  </testcase> <!-- bindcard -->
</testsuite> <!-- api.test.demo.Bindcard -->
